### ISSUE TITLE
Hello! Help for error  RuntimeError: Expected nested_tensorlist[0].size() > 0 to be true, but got false.

### ISSUE THREAD

**Issue by suted2** [MatteoSalvatori/INCE#6]
```
Building trainer...
Start training...
EPOCH: 1/100 - TRAINING:   0% 0/517 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/INCE/main.py", line 25, in <module>
    main()
  File "/content/INCE/main.py", line 20, in main
    to_opt()
  File "/content/INCE/src/trainers/standard_problem_to_opt.py", line 50, in __call__
    return trainer.train_model(brain=brain,
  File "/content/INCE/src/trainers/trainer.py", line 78, in train_model
    train_str = self.epoch_train(brain, optimizer, train_data, tot, epoch_shuffle_idx, batch_size, device, new_extra_text)
  File "/content/INCE/src/trainers/trainer.py", line 160, in epoch_train
    torch.nn.utils.clip_grad_value_(self.parameters(), 1.0)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/clip_grad.py", line 122, in clip_grad_value_
    grouped_grads = _group_tensors_by_device_and_dtype([grads])
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_foreach_utils.py", line 42, in _group_tensors_by_device_and_dtype
    torch._C._group_tensors_by_device_and_dtype(tensorlistlist, with_indices).items()
RuntimeError: Expected nested_tensorlist[0].size() > 0 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
EPOCH: 1/100 - TRAINING:   0% 0/517 [00:00<?, ?it/s]
```

hello i just do `python main.py ~ ` the code you mentioned 

but there's a error like this. 

even i do code step by step and no problem with device and code. 
this error ocurr every time ? 

How Can i solve it ?

**Comment by matteo-salvatori** [comment]
Hi @suted2 ,
Thank you for your message. 
We have been able to reproduce the problem and fix it. 
Let me know if everything is ok with the new version
Ciao

**Comment by suted2** [comment]
Oh It works well now !  @matteo-salvatori 
thanks a lot !  😊
